apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
spec:
  selector:
    app:  blog
  type:  {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.targetPort }}